export const POLITICS_KEYWORDS: readonly string[] = [
  'політик',
  'politician',
  'депутат',
  'deputy',
  'парламент',
  'parliament',
  'виборі',
  'виборч',
  'election',
  'electoral',
  'президент',
  'president',
  'уряд',
  'government',
  'партія',
  'партії',
  'party',
  'parties',
  'зеленський',
  'зеленського',
  'zelensky',
  'zelenskyy',
  'рада',
  'council',
  'закон',
  'law',
  'законопроект',
  'bill',
  'санкції',
  'санкцій',
  'sanction',
  'мер',
  'mayor',
  'губернатор',
  'governor',
  'реформ',
  'reform',
  'міністр',
  'minister',
  'кабмін',
  'cabinet',
  'верховн',
  'supreme',
  'голосуван',
  'vot',
  'референдум',
  'referendum',
  'мандат',
  'mandate',
  'фракці',
  'faction',
  'коаліці',
  'coalition',
  'банк',
  'bank',
];

export const WAR_KEYWORDS: readonly string[] = [
  'війн',
  'war',
  'обстріл',
  'shelling',
  'bombardment',
  'ракет',
  'missile',
  'фронт',
  'зброї',
  'зброй',
  'weapon',
  'arm',
  'окупант',
  'occupier',
  'invader',
  'окупаці',
  'мобілізація',
  'mobilization',
  'бойовий',
  'combat',
  'вибух',
  'explosion',
  'blast',
  'дрон',
  'drone',
  'ппо',
  'air defense',
  'десант',
  'landing',
  'paratrooper',
  'генштаб',
  'general staff',
  'артилері',
  'artillery',
  'снаряд',
  'shell',
  'projectile',
  'бомб',
  'bomb',
  'евакуаці',
  'зсу',
  'afu',
  'armed forces',
  'азов',
  'azov',
  'полон',
  'captivity',
  'pow',
  'поранен',
  'wound',
  'загибл',
  'dead',
  'killed',
  'гранат',
  'grenade',
];

export const CLICKBAIT_PATTERNS: readonly RegExp[] = [
  /^(чи|is|are|will|does|do|can|could|should|would) /i,
  /^(коли|when) /i,
  /^(що якщо|what if) /i,
  /^(як|how) /i,
  /\?$/,
  /(і це не|and it's not|and it is not)/i,
  /(ось чому|here is why|this is why|here's why)/i,
  /(ось як|here is how|this is how|here's how)/i,
  /(назвав клуб|named the club)/i,
  /(назвав гравц|named the player)/i,
  /(назвав трьох|named three)/i,
  /^(відео|video):/i,
  /^(фото|photo|photos):/i,
  /^(дивіться|watch):/i,
  /^(розкрито|revealed):/i,
  /^(оголошено|announced):/i,
  /(зірка|star) [a-zа-яіїєґ]+/i,
  /(клуб|club) [a-zа-яіїєґ]+/i,
  /(ціль|target) [a-zа-яіїєґ]+/i,
  /(екс-наставник|ex-manager|ex-coach|former manager|former coach)/i,
  /(прокоментував|commented on).*(майбутнє|чутки|призначення|ситуацію|трансфер|future|rumors|appointment|situation|transfer)/i,
  /(натякнув на|hinted at)/i,
  /(новий план|new plan).*(щодо|for|regarding)/i,
  /(інтерв'ю з|interview with).*(про|about) /i,
  /(останні новини щодо|latest news on|latest updates on)/i,
  /(оновлення про|update on)/i,
  /(ухвалив рішення щодо|made a decision on|decided on)/i,
  /(офіційну заяву|official statement)/i,
  /(надіслав повідомлення|sent a message)/i,
  /(вирішує|resolves|solves).*(питань|questions|issues)/i,
  /(склад|squad).*(несподіванок|surprises)/i,
];

export const NON_NEWS_PATTERNS: readonly RegExp[] = [
  /(повинен|must|should)/i,
  /(має бути|has to be|needs to be)/i,
  /(потрібно зупинити|needs to stop|must stop)/i,
  /(пряме висвітлення|live coverage)/i,
  /(покриття|coverage) .+sport/i,
  /(способи стеження|ways to follow|how to follow)/i,
];

export const GOSSIP_KEYWORDS: readonly string[] = [
  'романтичн',
  'romantic',
  'стосунк',
  'relationship',
  'пропозиці дружині',
  'proposal to wife',
  'пропозицію своїй дружині',
  'propose to his wife',
  'інфлюенсер',
  'influencer',
];
